/* Generated By:JavaCC: Do not edit this line. grammarConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int digit = 1;
  /** RegularExpression Id. */
  int letter = 2;
  /** RegularExpression Id. */
  int comp_op = 3;
  /** RegularExpression Id. */
  int data_type = 4;
  /** RegularExpression Id. */
  int literal_tok = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<digit>",
    "<letter>",
    "<comp_op>",
    "<data_type>",
    "<literal_tok>",
    "\".\"",
    "\" \"",
    "\", \"",
    "\"(\"",
    "\" + \"",
    "\" - \"",
    "\" * \"",
    "\")\"",
    "\" AND \"",
    "\" OR \"",
    "\"INSERT INTO \"",
    "\" (\"",
    "\" VALUES (\"",
    "\"DELETE FROM \"",
    "\" WHERE \"",
    "\"SELECT \"",
    "\"DISTINCT \"",
    "\"*\"",
    "\" FROM \"",
    "\" ORDER BY \"",
    "\"CREATE TABLE \"",
    "\"DROP TABLE \"",
    "\"\\n\"",
  };

}
